### ISSUE TITLE
InDesignフォームへの配置

### ISSUE THREAD

**Issue by sunohara** [naoya/md2inao#107]
@inao 

以下のInDesignへのテキスト取り込み手順の反映をお願いします。

# InDesignフォームへの配置

CUI版、Web版とも出力されたタグ付きテキストの文字コードを「Shift-JIS」、改行コードを「CR」に変更して再保存してください。
次にInDesignのマスターフォームを開き、作成したタグ付きテキストを配置します。
手順は次のとおりです。

1. **マスターフォームを開きます**
マスターフォームのファイルをダブルクリックして開いてください。

2. **「横組みグリッドツール」を選択します**
InDesignのツールボックス（デフォルトで左端に表示されるフローティングバー）にある「横組みグリッドツール」ボタンをクリックします。
「横組みグリッドツール」ボタンの場所が分からない場合は、（IMを英字入力に切り替えて）キーボードの「y」をタイプします。これで「横組みグリッドツール」ボタンをクリックしたのと同じことになります。
「横組みグリッドツール」を選択すると、マウスカーソルが細い十字のようなかたちに変わります。

3. **グリッドフレームを作成します**
マスターフォームに設定されているガイドに沿って、まず段組みの左段をドラッグします。左段の左上から右下へとマウスをドラッグすると、升目のついたフレームが作成されます。これがグリッドフレームです。

4. **タグ付きテキストを配置します**
先の手順で作成したグリッドフレームが選択されている状態（白い小さな□が付いている状態）で、メニューの「ファイル」→「配置...」を選択します。「配置」ダイアログが表示されますので、先ほど作成したタグ付きテキストを選択します。ダイアログ下部にある「グリッドフォーマットの適用」にチェックがついている場合はそれを外し、「開く」ボタンをクリックします。
「配置」ダイアログは、Command+Dでも表示できます。なお、グリッドフレームの選択が外れてしまった場合は、ツールボックスから「選択ツール」ボタン（黒い矢印）をクリックして、グリッドフレームをクリックし選択し直します。

5. **（テキストの続きを配置します）**
今回のサンプルテキストは短いので、上の手順までですべての読み込みが完了しますが、長いテキストの場合、左段だけではテキストが溢れてしまいます。溢れたテキストがある場合、グリッドフレームの右下に赤い四角が現れます。
溢れたテキストを配置するには、ツールボックスから「選択ツール」ボタン（黒い矢印のボタン）をクリックし、グリッドフレームの右下の赤い四角をクリックします。するとマウスカーソルにテキストの一部が表示されるようになります。
この状態で、マウスカーソルを右段の左上に持っていき、Shift+クリックします。すると、続きのテキストが自動的にすべて配置されます。

以上の手順で、グリッドにテキストが配置されたはずです。配置されたテキストには、すでにスタイルが適用されていることを確認してください。

**Comment by inao** [comment]
@sunohara 
ありがとうございます。
後日反映させますー。

**Comment by inao** [comment]
@sunohara 
改行コードは「CR」じゃなくてLFのままでOKですね。

**Comment by inao** [comment]
@sunohara 
対応しました！

**Comment by sunohara** [comment]
@inao 

確かにいつもは「LF」に変換していました。
対応ありがとうございます。
元ドキュメントが間違っているのか確認しましたが、この個所はなく私が追加したところだったので、私の勘違いでした。
