### ISSUE TITLE
行頭の半角スペースが全角スペースに置き換えられないようにする

### ISSUE THREAD

**Issue by inao** [naoya/md2inao#119]
@naoya 

すみません、けっこう困っておりまして、よろしければご相談にのっていただけないでしょうか？

# 現状
#4 で以下の機能を追加してくださいました。

> https://github.com/naoya/md2inao/issues/4#issuecomment-14599338
> 
> ですね。行頭がホワイトスペース 1〜3 で始まっていたら全角に置き換えます。
> ホワイトスペース4以上は、Markdown の場合 code ブロックになるので 1〜3 置き換えで全て例外ふくめ吸収できるはず。

当時は、ホワイトスペース4つによるcodeブロック表現しかなかったので全角スペースになっても問題なかったのですが、現状はGitHubのFenced code blocksのほうが普及してきたため、全角スペースに変換されたくないことがほとんどになってしまいました。

# 変更希望内容
「行頭がホワイトスペース 1〜3 で始まっていたら全角に置き換える」機能を削除していただくことは可能でしょうか？

手元でチャレンジしてみたのですが、うまくできませんでした。

# 受け入れテスト
以下、現状の変換結果と期待する変換結果です。

    --- in md2inao
    ```
    0
     1
      2
       3
        4
    ```
    --- 現状
    <ParaStyle:半行アキ>
    <ParaStyle:リスト>0
    <ParaStyle:リスト>　1
    <ParaStyle:リスト>　2
    <ParaStyle:リスト>　3
    <ParaStyle:リスト>    4
    --- expected
    <ParaStyle:半行アキ>
    <ParaStyle:リスト>0
    <ParaStyle:リスト> 1
    <ParaStyle:リスト>  2
    <ParaStyle:リスト>   3
    <ParaStyle:リスト>    4

# 補足
関連しまして、以下は、本文行頭に半角スペースを入れた場合の、現状の変換結果です。

こちらは本文なので、現状の変換結果のままでもかまいませんし、expectedの変換結果になるように変わってもかまいません。

    --- in md2inao
    0
    
     1
    
      2
    
       3
    
        4
    --- 現状
    <ParaStyle:本文>0
    <ParaStyle:本文>　1
    <ParaStyle:本文>　2
    <ParaStyle:本文>　3
    <ParaStyle:半行アキ>
    <ParaStyle:リスト>4
    --- expected
    <ParaStyle:本文>0
    <ParaStyle:本文>1
    <ParaStyle:本文>2
    <ParaStyle:本文>3
    <ParaStyle:半行アキ>
    <ParaStyle:リスト>4

なお、削除に伴い、全角スペースにまつわるそのほかの便利機能、たとえば #8 などの機能がなくなりましてもかまいません。

**Comment by naoya** [comment]
りょうかいです、ちょっと暇みつけてやりますね

**Comment by inao** [comment]
ありがとうございます！！！！ 🙇
