### ISSUE TITLE
数式を使い始めました。UseMath: true

### ISSUE THREAD

**Issue by tulamili** [naoya/md2inao#131]
数式を1個の段落に入れました。「ベン図」の所です。
数学に興味のある人の気を引くことが出来るので、良いことだろうと考えています。

**Comment by tulamili** [comment]
そうです。issueのたて間違えに該当するミスをしました。すいません。消し方が分からず、迷って、目立たないようにしたつもりが、issueは残ったままだと思います。

**Comment by inao** [comment]
閉じておきますね。
