### ISSUE TITLE
自動段落分け機能を削除する

### ISSUE THREAD

**Issue by murashitas** [naoya/md2inao#98]
https://github.com/naoya/md2inao#段落分け

「行頭で全角スペースによりインデントされている場合のみ、空行がなくても段落分けされ、上記の空行を入れた場合と同じ出力になります」とありますが、どうやら
- 2段落までであればうまくいく
- 3段落以上あると、3段落目以降が改段落されない

となってしまうようです。

---

たとえば、下記はうまくいきますが……

```
　こんにちはこんにちは。
　これが2段落目です！
```

下記は「こんにちはこんにちは。」のあとは改段落されるものの、「これが2段落目です！」のあとが改段落されません。

```
　こんにちはこんにちは。
　これが2段落目です！
　これが3段落目です!!
```

いちばん簡単な迂回策としてはREADMEの当該記述を削除してしまって、執筆時には空行を入れる方針にしてしまうことかと思っています。

**Comment by inao** [comment]
Normalラベルを付けました。

* 段落分け機能をなくし、READMEからも削除する
* 3段落目以降も段落分けされるようにしていただく（READMEどおりの挙動にしていただく）

**Comment by takahashim** [comment]
以下のpatchを適用すると、3段落目以降も段落されるようになります。

```diff
diff --git a/lib/Text/Md2Inao.pm b/lib/Text/Md2Inao.pm
index b4225d9..5223128 100644
--- a/lib/Text/Md2Inao.pm
+++ b/lib/Text/Md2Inao.pm
@@ -74,7 +74,9 @@ sub prepare_html_for_inao {
     $html =~ s!<li><p>(.+)</p></li>\n!<li>$1</li>\n!g;
 
     ## 段落切り替えの意図が見えるのにそうならないケースを補正 (issue #8)
-    $html =~ s!<p>(.*)\n　!<p>$1</p>\n<p>　!g;
+    while ($html =~ /<p>(.*)\n　/) {
+        $html =~ s!<p>(.*)\n　!<p>$1</p>\n<p>　!g;
+    }
     return $html;
 }
 ```

ですが、例えば以下のような、途中で行頭の全角空白がない行が混ざったようなケースだと、そもそもどういう結果になるべきなのか直感的に分からないので、いっそ全角空白による段落分け機能をなくした方がスッキリするのではないでしょうか。

```
=== paragraph separation with fullwidth-space
--- in md2id
　テスト。
　テスト2。
　テスト3。
　テスト4。
テスト5。
　テスト6。
　テスト7。

　テスト8。
　テスト9。
--- expected
<SJIS-MAC>
<ParaStyle:本文>　テスト。
<ParaStyle:本文>　テスト2。
<ParaStyle:本文>　テスト3。
<ParaStyle:本文>　テスト4。テスト5。　テスト6。　テスト7。
<ParaStyle:本文>　テスト8。
<ParaStyle:本文>　テスト9。
```

**Comment by inao** [comment]
> 以下のpatchを適用すると、3段落目以降も段落されるようになります。

ありがとうございます！

> いっそ全角空白による段落分け機能をなくした方がスッキリするのではないでしょうか。

おっしゃるとおりかと思います。
なくしていただけたりしますでしょうか…？

**Comment by inao** [comment]
@takahashim 

すみません、コードをご提案くださっていたのを今気がつきました……。
ありがとうございました。

#149 で反映させたので閉じます。
